// LEGACY SOURCE
export const LEGACY_EVENTSTORE_USERNAME_SRC =
  process.env.LEGACY_EVENTSTORE_USERNAME_SRC;
export const LEGACY_EVENTSTORE_PASSWORD_SRC =
  process.env.LEGACY_EVENTSTORE_PASSWORD_SRC;

export const LEGACY_EVENTSTORE_TCP_HOST_SOURCE =
  'localhost' || process.env.LEGACY_EVENTSTORE_TCP_HOST_SOURCE;
export const LEGACY_EVENTSTORE_TCP_PORT_SOURCE =
  +process.env.LEGACY_EVENTSTORE_TCP_PORT_SOURCE;

export const LEGACY_EVENTSTORE_HTTP_HOST_SOURCE =
  'localhost' || process.env.LEGACY_EVENTSTORE_HTTP_HOST_SOURCE;
export const LEGACY_EVENTSTORE_HTTP_PORT_SOURCE =
  +process.env.LEGACY_EVENTSTORE_HTTP_PORT_SOURCE;

// LEGACY DEST
export const LEGACY_EVENTSTORE_USERNAME_DEST =
  process.env.LEGACY_EVENTSTORE_USERNAME_DEST;
export const LEGACY_EVENTSTORE_PASSWORD_DEST =
  process.env.LEGACY_EVENTSTORE_PASSWORD_DEST;

export const LEGACY_EVENTSTORE_TCP_HOST_DEST =
  'localhost' || process.env.LEGACY_EVENTSTORE_TCP_HOST_DEST;
export const LEGACY_EVENTSTORE_TCP_PORT_DEST =
  +process.env.LEGACY_EVENTSTORE_TCP_PORT_DEST;

export const LEGACY_EVENTSTORE_HTTP_HOST_DEST =
  'localhost' || process.env.LEGACY_EVENTSTORE_HTTP_HOST_DEST;
export const LEGACY_EVENTSTORE_HTTP_PORT_DEST =
  +process.env.LEGACY_EVENTSTORE_HTTP_PORT_DEST;

// NEXT SOURCE
export const NEXT_EVENTSTORE_USERNAME_SRC =
  process.env.NEXT_EVENTSTORE_USERNAME_SRC;
export const NEXT_EVENTSTORE_PASSWORD_SRC =
  process.env.NEXT_EVENTSTORE_PASSWORD_SRC;

export const NEXT_EVENTSTORE_CONNECTION_STRING_SOURCE =
  process.env.NEXT_EVENTSTORE_CONNECTION_STRING_SOURCE;

// LEGACY DEST
export const NEXT_EVENTSTORE_USERNAME_DEST =
  process.env.NEXT_EVENTSTORE_USERNAME_DEST;
export const NEXT_EVENTSTORE_PASSWORD_DEST =
  process.env.NEXT_EVENTSTORE_PASSWORD_DEST;

export const NEXT_EVENTSTORE_CONNECTION_STRING_DEST =
  process.env.NEXT_EVENTSTORE_CONNECTION_STRING_DEST;
